from __future__ import annotations

from datetime import date
from typing import Optional
from uuid import UUID

from pydantic import (
    ConfigDict,
    EmailStr,
    Field,
    field_validator,
)

from app.common.enums.student import (
    BloodGroup,
    Gender,
    StudentStatus,
)
from app.schemas.base import (
    BaseResponseSchema,
    BaseSchema,
)


# ==========================================================
# Student Base
# ==========================================================


class StudentBase(BaseSchema):
    """
    Common student fields shared by
    Create and Update schemas.
    """

    # ------------------------------------------------------
    # Personal Information
    # ------------------------------------------------------

    first_name: str = Field(
        ...,
        min_length=2,
        max_length=100,
    )

    middle_name: Optional[str] = Field(
        default=None,
        max_length=100,
    )

    last_name: str = Field(
        ...,
        min_length=1,
        max_length=100,
    )

    gender: Gender

    blood_group: Optional[BloodGroup] = None

    date_of_birth: date

    # ------------------------------------------------------
    # Contact Information
    # ------------------------------------------------------

    email: Optional[EmailStr] = None

    phone: Optional[str] = Field(
        default=None,
        max_length=15,
    )

    emergency_contact: Optional[str] = Field(
        default=None,
        max_length=15,
    )

    # ------------------------------------------------------
    # Address
    # ------------------------------------------------------

    address_line1: str = Field(
        ...,
        max_length=255,
    )

    address_line2: Optional[str] = Field(
        default=None,
        max_length=255,
    )

    city: str = Field(
        ...,
        max_length=100,
    )

    district: str = Field(
        ...,
        max_length=100,
    )

    state: str = Field(
        ...,
        max_length=100,
    )

    country: str = Field(
        ...,
        max_length=100,
    )

    postal_code: str = Field(
        ...,
        max_length=10,
    )

    # ------------------------------------------------------
    # Academic Information
    # ------------------------------------------------------

    school_id: UUID

    parent_id: UUID

    academic_year_id: UUID

    school_class_id: UUID

    section_id: UUID

    admission_date: date

    status: StudentStatus = StudentStatus.ACTIVE

    # ------------------------------------------------------
    # Other
    # ------------------------------------------------------

    profile_photo_url: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    remarks: Optional[str] = Field(
        default=None,
        max_length=500,
    )

    # ======================================================
    # Validators
    # ======================================================

    @field_validator("date_of_birth")
    @classmethod
    def validate_date_of_birth(
        cls,
        value: date,
    ):
        if value > date.today():
            raise ValueError(
                "Date of birth cannot be in the future."
            )

        return value

    @field_validator("admission_date")
    @classmethod
    def validate_admission_date(
        cls,
        value: date,
    ):
        if value > date.today():
            raise ValueError(
                "Admission date cannot be in the future."
            )

        return value

    @field_validator(
        "phone",
        "emergency_contact",
    )
    @classmethod
    def validate_phone_numbers(
        cls,
        value: Optional[str],
    ):
        if value is None:
            return value

        digits = (
            value.replace(" ", "")
            .replace("-", "")
        )

        if not digits.isdigit():
            raise ValueError(
                "Phone number must contain only digits."
            )

        if len(digits) < 10:
            raise ValueError(
                "Phone number must contain at least 10 digits."
            )

        if len(digits) > 15:
            raise ValueError(
                "Phone number cannot exceed 15 digits."
            )

        return digits


# ==========================================================
# Create
# ==========================================================


class StudentCreate(StudentBase):
    """
    Schema used while creating a student.

    Admission Number and Roll Number are
    automatically generated by the service.
    """

    pass


# ==========================================================
# Update
# ==========================================================


class StudentUpdate(BaseSchema):
    """
    Partial student update schema.
    """

    model_config = ConfigDict(
        extra="forbid",
    )

    # ------------------------------------------------------
    # Personal Information
    # ------------------------------------------------------

    first_name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=100,
    )

    middle_name: Optional[str] = Field(
        default=None,
        max_length=100,
    )

    last_name: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=100,
    )

    gender: Optional[Gender] = None

    blood_group: Optional[BloodGroup] = None

    date_of_birth: Optional[date] = None

    # ------------------------------------------------------
    # Contact
    # ------------------------------------------------------

    email: Optional[EmailStr] = None

    phone: Optional[str] = None

    emergency_contact: Optional[str] = None

    # ------------------------------------------------------
    # Address
    # ------------------------------------------------------

    address_line1: Optional[str] = None

    address_line2: Optional[str] = None

    city: Optional[str] = None

    district: Optional[str] = None

    state: Optional[str] = None

    country: Optional[str] = None

    postal_code: Optional[str] = None

    # ------------------------------------------------------
    # Academic
    # ------------------------------------------------------

    parent_id: Optional[UUID] = None

    school_class_id: Optional[UUID] = None

    section_id: Optional[UUID] = None

    admission_date: Optional[date] = None

    status: Optional[StudentStatus] = None

    # ------------------------------------------------------
    # Other
    # ------------------------------------------------------

    profile_photo_url: Optional[str] = None

    remarks: Optional[str] = None

    @field_validator("date_of_birth")
    @classmethod
    def validate_date_of_birth(cls, value: Optional[date]):
        if value and value > date.today():
            raise ValueError("Date of birth cannot be in the future.")
        return value

    @field_validator("admission_date")
    @classmethod
    def validate_admission_date(cls, value: Optional[date]):
        if value and value > date.today():
            raise ValueError("Admission date cannot be in the future.")
        return value

    @field_validator("phone", "emergency_contact")
    @classmethod
    def validate_phone_numbers(cls, value: Optional[str]):
        if value is None:
            return value

        digits = value.replace(" ", "").replace("-", "")

        if not digits.isdigit():
            raise ValueError("Phone number must contain only digits.")

        if len(digits) < 10 or len(digits) > 15:
            raise ValueError("Invalid phone number.")

        return digits


    # ==========================================================
# Response
# ==========================================================


class StudentResponse(BaseResponseSchema):
    """
    Student response returned to clients.
    """

    # ------------------------------------------------------
    # Student Identity
    # ------------------------------------------------------

    admission_number: str

    roll_number: str

    status: StudentStatus

    # ------------------------------------------------------
    # Personal Information
    # ------------------------------------------------------

    first_name: str

    middle_name: Optional[str]

    last_name: str

    full_name: str

    gender: Gender

    blood_group: Optional[BloodGroup]

    date_of_birth: date

    # ------------------------------------------------------
    # Contact
    # ------------------------------------------------------

    email: Optional[EmailStr]

    phone: Optional[str]

    emergency_contact: Optional[str]

    # ------------------------------------------------------
    # Address
    # ------------------------------------------------------

    address_line1: str

    address_line2: Optional[str]

    city: str

    district: str

    state: str

    country: str

    postal_code: str

    # ------------------------------------------------------
    # Academic
    # ------------------------------------------------------

    school_id: UUID

    parent_id: UUID

    academic_year_id: UUID

    school_class_id: UUID

    section_id: UUID

    admission_date: date

    # ------------------------------------------------------
    # Other
    # ------------------------------------------------------

    profile_photo_url: Optional[str]

    remarks: Optional[str]

    model_config = ConfigDict(
        from_attributes=True,
    )


# ==========================================================
# Summary
# ==========================================================


class StudentSummary(BaseSchema):
    """
    Lightweight student information.
    """

    id: UUID

    admission_number: str

    roll_number: str

    full_name: str

    status: StudentStatus

    model_config = ConfigDict(
        from_attributes=True,
    )


# ==========================================================
# Filter
# ==========================================================


class StudentFilter(BaseSchema):
    """
    Student search and filter schema.
    """

    search: Optional[str] = Field(
        default=None,
        max_length=100,
    )

    school_id: Optional[UUID] = None

    academic_year_id: Optional[UUID] = None

    school_class_id: Optional[UUID] = None

    section_id: Optional[UUID] = None

    parent_id: Optional[UUID] = None

    gender: Optional[Gender] = None

    status: Optional[StudentStatus] = None

    page: int = Field(
        default=1,
        ge=1,
    )

    page_size: int = Field(
        default=10,
        ge=1,
        le=100,
    )

    sort_by: str = Field(
    default="created_at",
    max_length=50,
)

sort_order: str = Field(
    default="desc",
    pattern="^(asc|desc)$",
)


# ==========================================================
# List Response
# ==========================================================


class StudentListResponse(BaseSchema):
    """
    Paginated student response.
    """

    items: list[StudentResponse]

    total: int

    page: int

    page_size: int

    total_pages: int

    model_config = ConfigDict(
        from_attributes=True,
    )