"""create_school_classes_table

Revision ID: 009d11cf0565
Revises: 0e00ee3aff67
Create Date: 2026-07-25 16:13:03.389544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009d11cf0565'
down_revision: Union[str, Sequence[str], None] = '0e00ee3aff67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='school_class_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_school_class_name')
    )
    op.create_index('ix_school_classes_display_order', 'school_classes', ['display_order'], unique=False)
    op.create_index('ix_school_classes_school_id', 'school_classes', ['school_id'], unique=False)
    op.create_index('ix_school_classes_status', 'school_classes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_school_classes_status', table_name='school_classes')
    op.drop_index('ix_school_classes_school_id', table_name='school_classes')
    op.drop_index('ix_school_classes_display_order', table_name='school_classes')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
