"""create core school models

Revision ID: 04b289984b39
Revises: 49fb21c79fc9
Create Date: 2026-07-26 20:52:02.453837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b289984b39'
down_revision: Union[str, Sequence[str], None] = '49fb21c79fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_academic_year_start_date', 'academic_years', ['start_date'], unique=False)
    op.create_index('ix_parents_email', 'parents', ['email'], unique=False)
    op.create_index('ix_parents_is_active', 'parents', ['is_active'], unique=False)
    op.create_index('ix_parents_primary_phone', 'parents', ['primary_phone'], unique=False)
    op.create_index('ix_parents_school_id', 'parents', ['school_id'], unique=False)
    is_sqlite = op.get_bind().dialect.name == 'sqlite'
    if not is_sqlite:
        op.drop_constraint(op.f('parents_school_id_fkey'), 'parents', type_='foreignkey')
        op.create_foreign_key(None, 'parents', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('uq_school_class_name'), 'school_classes', type_='unique')
        op.create_unique_constraint('uq_school_classes_school_id_name', 'school_classes', ['school_id', 'name'])
        op.drop_constraint(op.f('uq_section_name'), 'sections', type_='unique')
        op.create_unique_constraint('uq_sections_school_class_id_name', 'sections', ['school_class_id', 'name'])
    op.add_column('students', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('emergency_contact', sa.String(length=15), nullable=True))
    op.add_column('students', sa.Column('profile_photo_url', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('remarks', sa.String(length=500), nullable=True))
    op.create_index('ix_students_admission_number', 'students', ['admission_number'], unique=False)
    op.create_index('ix_students_first_name', 'students', ['first_name'], unique=False)
    op.create_index('ix_students_last_name', 'students', ['last_name'], unique=False)
    op.create_index('ix_students_roll_number', 'students', ['roll_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_roll_number', table_name='students')
    op.drop_index('ix_students_last_name', table_name='students')
    op.drop_index('ix_students_first_name', table_name='students')
    op.drop_index('ix_students_admission_number', table_name='students')
    op.drop_column('students', 'remarks')
    op.drop_column('students', 'profile_photo_url')
    op.drop_column('students', 'emergency_contact')
    op.drop_column('students', 'middle_name')
    op.drop_constraint('uq_sections_school_class_id_name', 'sections', type_='unique')
    op.create_unique_constraint(op.f('uq_section_name'), 'sections', ['school_class_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_school_classes_school_id_name', 'school_classes', type_='unique')
    op.create_unique_constraint(op.f('uq_school_class_name'), 'school_classes', ['school_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.create_foreign_key(op.f('parents_school_id_fkey'), 'parents', 'schools', ['school_id'], ['id'])
    op.drop_index('ix_parents_school_id', table_name='parents')
    op.drop_index('ix_parents_primary_phone', table_name='parents')
    op.drop_index('ix_parents_is_active', table_name='parents')
    op.drop_index('ix_parents_email', table_name='parents')
    op.drop_index('ix_academic_year_start_date', table_name='academic_years')
    # ### end Alembic commands ###
