"""create academic_years table

Revision ID: 0e00ee3aff67
Revises: 278cbfe15e09
Create Date: 2026-07-25 13:06:20.532407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e00ee3aff67'
down_revision: Union[str, Sequence[str], None] = '278cbfe15e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'ARCHIVED', name='academic_year_status'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_academic_year_school_name')
    )
    op.create_index('ix_academic_year_current', 'academic_years', ['is_current'], unique=False)
    op.create_index('ix_academic_year_school_id', 'academic_years', ['school_id'], unique=False)
    op.create_index('ix_academic_year_status', 'academic_years', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_academic_year_status', table_name='academic_years')
    op.drop_index('ix_academic_year_school_id', table_name='academic_years')
    op.drop_index('ix_academic_year_current', table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
