"""create_students_table

Revision ID: 49fb21c79fc9
Revises: 009d11cf0565
Create Date: 2026-07-26 16:31:56.681361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fb21c79fc9'
down_revision: Union[str, Sequence[str], None] = '009d11cf0565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('school_class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='section_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_class_id', 'name', name='uq_section_name')
    )
    op.create_index('ix_sections_name', 'sections', ['name'], unique=False)
    op.create_index('ix_sections_school_class_id', 'sections', ['school_class_id'], unique=False)
    op.create_index('ix_sections_status', 'sections', ['status'], unique=False)
    op.create_table('students',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('school_class_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('admission_number', sa.String(length=30), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('blood_group', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', 'UNKNOWN', name='blood_group'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'TRANSFERRED', 'PASSED_OUT', 'DROPPED', name='student_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'school_class_id', 'roll_number', name='uq_student_roll_number'),
    sa.UniqueConstraint('admission_number', name='uq_student_admission_number')
    )
    op.create_index('ix_students_class_id', 'students', ['school_class_id'], unique=False)
    op.create_index('ix_students_parent_id', 'students', ['parent_id'], unique=False)
    op.create_index('ix_students_school_id', 'students', ['school_id'], unique=False)
    op.create_index('ix_students_section_id', 'students', ['section_id'], unique=False)
    op.create_index('ix_students_status', 'students', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_students_status', table_name='students')
    op.drop_index('ix_students_section_id', table_name='students')
    op.drop_index('ix_students_school_id', table_name='students')
    op.drop_index('ix_students_parent_id', table_name='students')
    op.drop_index('ix_students_class_id', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_sections_status', table_name='sections')
    op.drop_index('ix_sections_school_class_id', table_name='sections')
    op.drop_index('ix_sections_name', table_name='sections')
    op.drop_table('sections')
    # ### end Alembic commands ###
