"""
AI Communication Draft database model definition for Phase 12.5.
Stores multi-channel announcement and notice draft proposals generated by AI.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, TYPE_CHECKING

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship as orm_relationship

from app.database.common_model import CommonModel

if TYPE_CHECKING:
    from app.identity.models.user import IdentityUser
    from app.models.school.school import School


class AICommunicationDraft(CommonModel):
    """
    Represents an AI-generated communication or announcement draft proposal.
    Non-custodial: saved as DRAFT until reviewed and sent via Notification Subsystem.
    """

    __tablename__ = "ai_communication_drafts"

    school_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("identity_users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    category: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="ANNOUNCEMENT",
        index=True,
    )  # ANNOUNCEMENT, ACADEMIC_NOTICE, EMERGENCY_ALERT, EVENT_INVITATION, PARENT_UPDATE

    target_audience: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="PARENTS",
    )  # PARENTS, STUDENTS, TEACHERS, ALL_STAFF

    tone: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="FORMAL",
    )  # FORMAL, URGENT, FRIENDLY, ENCOURAGING

    prompt_summary: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    channel_variants: Mapped[dict[str, Any]] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
        default=dict,
    )  # {"SMS": {"title": "", "body": ""}, "EMAIL": {...}, "WHATSAPP": {...}, "IN_APP": {...}}

    pii_redact_log: Mapped[list[str]] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
        default=list,
    )  # List of redacted PII categories/keys

    token_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="DRAFT",
        index=True,
    )  # DRAFT, APPROVED, DISPATCHED, DISCARDED

    assessed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    school: Mapped["School"] = orm_relationship("School")
    created_by_user: Mapped["IdentityUser | None"] = orm_relationship("IdentityUser")

    __table_args__ = (
        Index("idx_ai_comm_school_category", "school_id", "category"),
        Index("idx_ai_comm_school_created", "school_id", "created_at"),
    )
