"""
AI Report Card Remark database model definition for Phase 12.6.
Stores qualitative student performance evaluation remarks, subject strengths,
focus areas, and actionable recommendations generated by AI.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, TYPE_CHECKING

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship as orm_relationship

from app.database.common_model import CommonModel

if TYPE_CHECKING:
    from app.identity.models.user import IdentityUser
    from app.models.grading.report_card import ReportCard
    from app.models.school.school import School
    from app.models.student.student import Student


class AIReportCardRemark(CommonModel):
    """
    Represents an AI-generated qualitative report card remarks proposal.
    Non-custodial: saved as DRAFT until reviewed, edited, or applied to ReportCard.
    """

    __tablename__ = "ai_report_card_remarks"

    school_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("schools.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    report_card_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("report_cards.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    student_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("identity_users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    tone: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="BALANCED",
    )  # BALANCED, ENCOURAGING, DIRECT, ACADEMIC_FOCUS

    detail_level: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="DETAILED",
    )  # CONCISE, DETAILED

    teacher_remarks_draft: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    principal_remarks_draft: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    action_items: Mapped[list[str]] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
        default=list,
    )  # List of 2-3 specific action items for parents and student

    strength_subjects: Mapped[list[str]] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
        default=list,
    )  # List of top performing subjects

    focus_subjects: Mapped[list[str]] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
        default=list,
    )  # List of subjects needing academic remediation

    token_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="DRAFT",
        index=True,
    )  # DRAFT, ACCEPTED, MODIFIED, DISCARDED

    assessed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    school: Mapped["School"] = orm_relationship("School")
    report_card: Mapped["ReportCard"] = orm_relationship("ReportCard")
    student: Mapped["Student"] = orm_relationship("Student")
    created_by_user: Mapped["IdentityUser | None"] = orm_relationship("IdentityUser")

    __table_args__ = (
        Index("idx_ai_remark_school_card", "school_id", "report_card_id"),
        Index("idx_ai_remark_school_student", "school_id", "student_id"),
    )
